# Generated by Django 2.2.4 on 2022-12-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20221225_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='agr',
            new_name='age',
        ),
    ]
