# Generated by Django 2.2.4 on 2022-12-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Blank'),
            preserve_default=False,
        ),
    ]
