# Generated by Django 2.2.4 on 2022-12-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agr',
            field=models.IntegerField(),
        ),
    ]
